package practica1;
// Generated 29/02/2016 11:11:47 PM by Hibernate Tools 4.3.1



/**
 * Cuentas generated by hbm2java
 */
public class Cuentas  implements java.io.Serializable {


     private int idusuario;
     private Usuarios usuarios;
     private String usuario;
     private String pass;

    public Cuentas() {
    }

	
    public Cuentas(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Cuentas(Usuarios usuarios, String usuario, String pass) {
       this.usuarios = usuarios;
       this.usuario = usuario;
       this.pass = pass;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


